### ISSUE TITLE
port to python?

### ISSUE THREAD

**Issue by kivaacts** [alexellis/mongodb-function#2]
We tried porting this to python (below), but it seems that the module is reloaded every time, as the cache is always `None`. Is this functionality available only in node? Do you know of a workaround for python?

Thanks!

```
import os
import pymongo
import json

mongo_client = None

def handle(req):
    """
    create a record,
    get the database, get the users collection from the database,
    and insert the record into the collection.
    return a result, setting status appropriately
    """

    record = json.loads(req)
    db = prepareDB()
    users = db.users
    id = users.insert_one(record).inserted_id
    return {
      'status': 'Inserted record with id {}: {}'.format(
        id, record)
    }

def prepareDB():
    global mongo_client

    if mongo_client is None:
        url = "mongodb://" + os.environ["mongo"] + ":27017"
        mongo_client = pymongo.MongoClient(url)
    return mongo_client.clients
```

**Comment by alexellis** [comment]
Yes it's possible. Are you using the template for Flask? 

https://github.com/openfaas-incubator/python-flask-template

**Comment by kivaacts** [comment]
Hi Alex, 

Thank you so much for your quick response! We were able to get it to work using the Python27-flask template, but did have problems when trying to use the Python3-flask template. 

Thanks :)

**Comment by alexellis** [comment]
That's great! Want to do a PR here then? What problem did you run into?
